import type { Metadata } from "next";
import { Geist, Geist_Mono, Nunito_Sans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Card, CardHeader } from "@/components/ui/card";
import Link from "next/link";
import { Button } from "@/components/ui/button";

const nunitoSans = Nunito_Sans({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        geistSans.variable,
        geistMono.variable,
        "font-sans",
        nunitoSans.variable,
      )}
    >
      <body>
        <div className="relative flex flex-row w-min p-4">
          <div className="absolute top-1/2 -translate-y-1/2 text-sm">
            Simple Tickets Application
          </div>
          <div className="flex flex-row items-center justify-center space-x-4 w-screen">
            <Link href="tickets" className="hover:cursor-pointer">
              <Button>Tickets</Button>
            </Link>
            <Link href="profile" className="hover:cursor-pointer">
              <Button>Perfil</Button>
            </Link>
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
